title: Mind of a developer
description: tadam313 personal blog about software engineering/tech/random thought-flow from my mind.
tagline: Math.random()

# Sass compilation
sass:
  sass_dir: assets/stylesheets/scss
  style: compressed

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
author:
  name: tadam313
  email: adam.pelle.peter@gmail.com
  bio: 'Software engineer and musician'
  twitter: 'https://twitter.com/tadam313'
  facebook: 'http://facebook.com/adam.pelle313'
  linkedin: 'https://hu.linkedin.com/pub/adam-pelle/52/467/798'

url: 'http://tadam313.github.io'

# general setting for Jekyll
# googleAnalytics: UA-XXXXX-X

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-coffeescript

# Enables future posts (posts with dates in the future) and drafts
future: false
show_drafts: false
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Pagination options
permalink: pretty
paginate: 10
paginate_path: 'page:num'

# Markdown library
markdown: kramdown
highlighter: rouge
