title: Adam's blog
description: Adam's blog
tagline: '< /dev/urandom'

show_excerpts: true

sass:
  sass_dir: assets/stylesheets
  style: compressed

texture:
  title: Adam's blog
  tagline: Nerd. Gamer. Cycler. Musician.
  style: blue
  showNav: true
  date_format: "%b %-d, %Y"

  social_links:
    twitter: tadam313
    github:  tadam313
    linkedIn: in/adam-pelle-79846752

theme: texture
remote_theme: thelehhman/texture

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
author:
  name: tadam313
  email: adam.pelle.peter@gmail.com

url: 'http://tadam313.github.io'

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-coffeescript

# # Pagination options
# permalink: pretty
# paginate: 10
# paginate_path: 'page:num'

# # Markdown library
# markdown: kramdown
# highlighter: rouge
